#!/bin/bash
red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

BASEDIR=$(dirname $0)

CPP=".cpp"
HPP=".hpp"
_HPP="_HPP"
CLASS=".class"

read -p 'Enter prefixe of your .hpp/.cpp : ' filename

if [ -z "$filename" ]; 
then
	echo "${red}Empty filename${reset}"
	exit 1
fi
echo "${green}Creating $filename Coplienne class${reset}"

hppHeader="${filename^^}$_HPP"
fileHPP="$filename$CLASS$HPP"
fileCPP="$filename$CLASS$CPP"

#Creating files
touch $fileHPP
touch $fileCPP

#Writing in HPP
cat ${BASEDIR}//srcs/ClassHPP > $fileHPP
sed -i -e "s/user_HPP_name/$hppHeader/g" $fileHPP
sed -i -e "s/__user_class_name/$filename/g" $fileHPP

echo "${green}$filename.hpp : Done.${reset}"

#Writing in CPP
cat ${BASEDIR}//srcs/ClassCPP > $fileCPP
sed -i -e "s/__user_class_name/$filename/g" $fileCPP

echo "${green}$filename.cpp : Done.${reset}"